services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:4.34.0
    restart: unless-stopped
    ports:
      - ${APP_PORT}:4444
    shm_size: 2g
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.selenium-redirect.redirectscheme.scheme: https
      traefik.http.services.selenium.loadbalancer.server.port: 4444
      # Web
      traefik.http.routers.selenium-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.selenium-insecure.entrypoints: web
      traefik.http.routers.selenium-insecure.service: selenium
      traefik.http.routers.selenium-insecure.middlewares: selenium-redirect
      # Websecure
      traefik.http.routers.selenium.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.selenium.entrypoints: websecure
      traefik.http.routers.selenium.service: selenium
      traefik.http.routers.selenium.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.selenium-custom-local-insecure.rule: Host(`selenium.${LOCAL_DOMAIN}`)
      traefik.http.routers.selenium-custom-local-insecure.entrypoints: web
      traefik.http.routers.selenium-custom-local-insecure.service: selenium
      traefik.http.routers.selenium-custom-local-insecure.middlewares: selenium-redirect
      # Local domain secure
      traefik.http.routers.selenium-custom-local.rule: Host(`selenium.${LOCAL_DOMAIN}`)
      traefik.http.routers.selenium-custom-local.entrypoints: websecure
      traefik.http.routers.selenium-custom-local.service: selenium
      traefik.http.routers.selenium-custom-local.tls: true
      runtipi.managed: true
